//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bookmark")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub url: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bookmark_tag::Entity")]
    BookmarkTag,
}

impl Related<super::bookmark_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookmarkTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
