name: ci
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test:
    name: Test
    env:
      TARGET_FLAGS:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - stable
        - beta
        - nightly
        include:
        - build: stable
          os: ubuntu-latest
          rust: stable
        - build: beta
          os: ubuntu-latest
          rust: beta
        - build: nightly
          os: ubuntu-latest
          rust: nightly
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Show target flags
      run: |
        echo "target flag is: ${{ env.TARGET_FLAGS }}"
    - name: Run check
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
      with:
        command: check
        args: --verbose --workspace ${{ env.TARGET_FLAGS }}
    - name: Run clean
      if: matrix.build == 'nightly'
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
      with:
        command: clean
    - name: Run tests
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
      with:
        command: test
        args: --verbose --workspace ${{ env.TARGET_FLAGS }}

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy
    - uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Check documentation
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
      with:
        command: doc
        args: --no-deps --document-private-items --workspace
